import type { PresetLanguage } from '../defaults/regionalPresets';

/**
 * Curated, per-region lists of everyday sites — the pool the "add from
 * catalog" picker offers for Shortcuts and the Dock, and the source the
 * first-run Dock / Shortcut defaults are derived from (`regionalPresets`).
 *
 * Aimed at the general public of each region, not developers: portals,
 * mail, maps, video, social, shopping, news, travel, banks, AI. Titles and
 * categories are already in the region's language because they are stored
 * verbatim in the user's data (the Shortcuts widget uses free-text
 * categories).
 *
 * `dock` / `shortcut` are 1-based ranks in the first-run defaults; entries
 * without them are catalog-only.
 */
export interface CatalogSite {
  /** Stable id, also the suffix of the default `dock-<id>` / `app-<id>` item ids. */
  id: string;
  title: string;
  url: string;
  /** Localized category label (chip in the picker, category in the widget). */
  category: string;
  /** DOCK_ICON_LIBRARY key used when the site lands in the Dock. */
  icon: string;
  /** Position in the first-run Dock (1 = leftmost). */
  dock?: number;
  /** Position in the first-run Shortcuts widget. */
  shortcut?: number;
  /** Dock label when it should differ from `title` (e.g. Latin script in the Dock). */
  dockLabel?: string;
}

type Row = [id: string, title: string, url: string, category: string, icon: string, dock?: number, shortcut?: number, dockLabel?: string];

const rows = (list: Row[]): CatalogSite[] =>
  list.map(([id, title, url, category, icon, dock, shortcut, dockLabel]) => ({
    id,
    title,
    url,
    category,
    icon,
    ...(dock ? { dock } : {}),
    ...(shortcut ? { shortcut } : {}),
    ...(dockLabel ? { dockLabel } : {}),
  }));

/** Stable category keys behind the localized labels (used by the first-run setup's interest mapping). */
export type SiteCategoryKey = 'daily' | 'social' | 'video' | 'shop' | 'ai' | 'news' | 'travel' | 'money' | 'learn' | 'work';

// Category labels per language, so every entry of a region uses the same
// spelling (the picker groups by exact string).
const EN = { daily: 'Everyday', social: 'Social', video: 'Entertainment', shop: 'Shopping', ai: 'AI & Tools', news: 'News', travel: 'Travel & Local', money: 'Finance', learn: 'Learning', work: 'Work' };
const JA = { daily: '仕事・日常', social: 'SNS・動画', video: 'エンタメ', shop: 'ショッピング', ai: 'AI・ツール', news: 'ニュース', travel: '交通・旅行', money: 'お金', learn: '学習', work: '仕事' };
const KO = { daily: '일상', social: 'SNS·동영상', video: '엔터테인먼트', shop: '쇼핑', ai: 'AI·도구', news: '뉴스', travel: '교통·여행', money: '금융', learn: '학습', work: '업무' };
const ZH = { daily: '日常', social: '社交·视频', video: '娱乐', shop: '购物', ai: 'AI·工具', news: '新闻', travel: '出行·旅游', money: '金融', learn: '学习', work: '办公' };
const ES = { daily: 'Día a día', social: 'Redes y vídeo', video: 'Entretenimiento', shop: 'Compras', ai: 'IA y herramientas', news: 'Noticias', travel: 'Viajes y transporte', money: 'Finanzas', learn: 'Aprender', work: 'Trabajo' };
const FR = { daily: 'Quotidien', social: 'Réseaux et vidéo', video: 'Divertissement', shop: 'Shopping', ai: 'IA et outils', news: 'Actualités', travel: 'Voyages et transports', money: 'Finances', learn: 'Apprendre', work: 'Travail' };
const DE = { daily: 'Alltag', social: 'Social & Video', video: 'Unterhaltung', shop: 'Shopping', ai: 'KI & Tools', news: 'Nachrichten', travel: 'Reisen & Verkehr', money: 'Finanzen', learn: 'Lernen', work: 'Arbeit' };

export const SITE_CATEGORY_LABELS: Record<PresetLanguage, Record<SiteCategoryKey, string>> = {
  en: EN,
  ja: JA,
  ko: KO,
  'zh-CN': ZH,
  es: ES,
  fr: FR,
  de: DE,
};

const SITES: Record<PresetLanguage, CatalogSite[]> = {
  en: rows([
    ['google', 'Google', 'https://google.com', EN.daily, 'globe', 1, 1],
    ['youtube', 'YouTube', 'https://youtube.com', EN.video, 'video', 2, 2],
    ['amazon', 'Amazon', 'https://www.amazon.com', EN.shop, 'cart', 3, 4],
    ['chatgpt', 'ChatGPT', 'https://chatgpt.com', EN.ai, 'sparkles', 4, 3],
    ['maps', 'Google Maps', 'https://maps.google.com', EN.daily, 'map', 5, 11],
    ['wikipedia', 'Wikipedia', 'https://www.wikipedia.org', EN.daily, 'book', 6, 12],
    ['reddit', 'Reddit', 'https://reddit.com', EN.social, 'chat', undefined, 5],
    ['instagram', 'Instagram', 'https://instagram.com', EN.social, 'camera', undefined, 6],
    ['twitter', 'X (Twitter)', 'https://x.com', EN.social, 'chat', undefined, 7],
    ['netflix', 'Netflix', 'https://netflix.com', EN.video, 'movie', undefined, 8],
    ['spotify', 'Spotify', 'https://open.spotify.com', EN.video, 'music', undefined, 9],
    ['gmail', 'Gmail', 'https://mail.google.com', EN.daily, 'mail', undefined, 10],
    ['outlook', 'Outlook', 'https://outlook.live.com', EN.daily, 'mail'],
    ['gcal', 'Google Calendar', 'https://calendar.google.com', EN.daily, 'calendar'],
    ['gdrive', 'Google Drive', 'https://drive.google.com', EN.work, 'folder'],
    ['gdocs', 'Google Docs', 'https://docs.google.com', EN.work, 'document'],
    ['translate', 'Google Translate', 'https://translate.google.com', EN.daily, 'globe'],
    ['facebook', 'Facebook', 'https://www.facebook.com', EN.social, 'people'],
    ['tiktok', 'TikTok', 'https://www.tiktok.com', EN.social, 'video'],
    ['whatsapp', 'WhatsApp', 'https://web.whatsapp.com', EN.social, 'chat'],
    ['discord', 'Discord', 'https://discord.com/app', EN.social, 'headphones'],
    ['pinterest', 'Pinterest', 'https://www.pinterest.com', EN.social, 'design'],
    ['twitch', 'Twitch', 'https://www.twitch.tv', EN.video, 'game'],
    ['disney', 'Disney+', 'https://www.disneyplus.com', EN.video, 'tv'],
    ['primevideo', 'Prime Video', 'https://www.primevideo.com', EN.video, 'movie'],
    ['applemusic', 'Apple Music', 'https://music.apple.com', EN.video, 'music'],
    ['ebay', 'eBay', 'https://www.ebay.com', EN.shop, 'tag'],
    ['walmart', 'Walmart', 'https://www.walmart.com', EN.shop, 'cart'],
    ['etsy', 'Etsy', 'https://www.etsy.com', EN.shop, 'gift'],
    ['temu', 'Temu', 'https://www.temu.com', EN.shop, 'package'],
    ['gemini', 'Gemini', 'https://gemini.google.com', EN.ai, 'sparkles'],
    ['claude', 'Claude', 'https://claude.ai', EN.ai, 'sparkles'],
    ['copilot', 'Copilot', 'https://copilot.microsoft.com', EN.ai, 'sparkles'],
    ['perplexity', 'Perplexity', 'https://www.perplexity.ai', EN.ai, 'compass'],
    ['canva', 'Canva', 'https://www.canva.com', EN.ai, 'design'],
    ['bbc', 'BBC News', 'https://www.bbc.com/news', EN.news, 'news'],
    ['cnn', 'CNN', 'https://www.cnn.com', EN.news, 'news'],
    ['nytimes', 'The New York Times', 'https://www.nytimes.com', EN.news, 'news'],
    ['guardian', 'The Guardian', 'https://www.theguardian.com', EN.news, 'news'],
    ['weather', 'Weather.com', 'https://weather.com', EN.daily, 'cloud'],
    ['booking', 'Booking.com', 'https://www.booking.com', EN.travel, 'travel'],
    ['airbnb', 'Airbnb', 'https://www.airbnb.com', EN.travel, 'home'],
    ['uber', 'Uber', 'https://m.uber.com', EN.travel, 'car'],
    ['paypal', 'PayPal', 'https://www.paypal.com', EN.money, 'wallet'],
    ['yahoofinance', 'Yahoo Finance', 'https://finance.yahoo.com', EN.money, 'trending'],
    ['linkedin', 'LinkedIn', 'https://www.linkedin.com', EN.work, 'work'],
    ['notion', 'Notion', 'https://www.notion.so', EN.work, 'document'],
    ['duolingo', 'Duolingo', 'https://www.duolingo.com', EN.learn, 'study'],
    ['coursera', 'Coursera', 'https://www.coursera.org', EN.learn, 'library'],
    ['khan', 'Khan Academy', 'https://www.khanacademy.org', EN.learn, 'study'],
  ]),

  ja: rows([
    ['google', 'Google', 'https://google.com', JA.daily, 'globe', 1, 1],
    ['youtube', 'YouTube', 'https://youtube.com', JA.social, 'video', 2, 2],
    ['twitter', 'X (Twitter)', 'https://x.com', JA.social, 'chat', 3, 3],
    ['yahoo-jp', 'Yahoo! JAPAN', 'https://www.yahoo.co.jp', JA.daily, 'news', 4, 4],
    ['amazon-jp', 'Amazon', 'https://www.amazon.co.jp', JA.shop, 'cart', 5, 5],
    ['chatgpt', 'ChatGPT', 'https://chatgpt.com', JA.ai, 'sparkles', 6, 8],
    ['rakuten', '楽天市場', 'https://www.rakuten.co.jp', JA.shop, 'cart', undefined, 6],
    ['instagram', 'Instagram', 'https://instagram.com', JA.social, 'camera', undefined, 7],
    ['gmail', 'Gmail', 'https://mail.google.com', JA.daily, 'mail', undefined, 9],
    ['maps', 'Google マップ', 'https://maps.google.com', JA.daily, 'map', undefined, 10],
    ['spotify', 'Spotify', 'https://open.spotify.com', JA.video, 'music', undefined, 11],
    ['netflix', 'Netflix', 'https://netflix.com', JA.video, 'movie', undefined, 12],
    ['line', 'LINE', 'https://line.me/ja/', JA.social, 'chat'],
    ['tiktok', 'TikTok', 'https://www.tiktok.com', JA.social, 'video'],
    ['niconico', 'ニコニコ動画', 'https://www.nicovideo.jp', JA.social, 'tv'],
    ['abema', 'ABEMA', 'https://abema.tv', JA.video, 'tv'],
    ['tver', 'TVer', 'https://tver.jp', JA.video, 'tv'],
    ['primevideo-jp', 'Prime Video', 'https://www.amazon.co.jp/gp/video/storefront', JA.video, 'movie'],
    ['unext', 'U-NEXT', 'https://video.unext.jp', JA.video, 'movie'],
    ['disney-jp', 'Disney+', 'https://www.disneyplus.com/ja-jp', JA.video, 'tv'],
    ['radiko', 'radiko', 'https://radiko.jp', JA.video, 'mic'],
    ['pixiv', 'pixiv', 'https://www.pixiv.net', JA.social, 'design'],
    ['yahoo-shopping', 'Yahoo!ショッピング', 'https://shopping.yahoo.co.jp', JA.shop, 'cart'],
    ['mercari', 'メルカリ', 'https://jp.mercari.com', JA.shop, 'tag'],
    ['zozo', 'ZOZOTOWN', 'https://zozo.jp', JA.shop, 'package'],
    ['kakaku', '価格.com', 'https://kakaku.com', JA.shop, 'tag'],
    ['uniqlo', 'ユニクロ', 'https://www.uniqlo.com/jp/ja/', JA.shop, 'package'],
    ['gemini', 'Gemini', 'https://gemini.google.com', JA.ai, 'sparkles'],
    ['claude', 'Claude', 'https://claude.ai', JA.ai, 'sparkles'],
    ['copilot', 'Copilot', 'https://copilot.microsoft.com', JA.ai, 'sparkles'],
    ['deepl', 'DeepL', 'https://www.deepl.com/translator', JA.ai, 'globe'],
    ['translate', 'Google 翻訳', 'https://translate.google.com', JA.ai, 'globe'],
    ['canva', 'Canva', 'https://www.canva.com', JA.ai, 'design'],
    ['nhk', 'NHK ニュース', 'https://www3.nhk.or.jp/news/', JA.news, 'news'],
    ['yahoo-news', 'Yahoo!ニュース', 'https://news.yahoo.co.jp', JA.news, 'news'],
    ['nikkei', '日本経済新聞', 'https://www.nikkei.com', JA.news, 'news'],
    ['itmedia', 'ITmedia', 'https://www.itmedia.co.jp', JA.news, 'news'],
    ['tenki', 'tenki.jp', 'https://tenki.jp', JA.daily, 'cloud'],
    ['yahoo-transit', 'Yahoo!乗換案内', 'https://transit.yahoo.co.jp', JA.travel, 'train'],
    ['jorudan', 'ジョルダン', 'https://www.jorudan.co.jp', JA.travel, 'train'],
    ['jalan', 'じゃらん', 'https://www.jalan.net', JA.travel, 'travel'],
    ['rakuten-travel', '楽天トラベル', 'https://travel.rakuten.co.jp', JA.travel, 'travel'],
    ['tabelog', '食べログ', 'https://tabelog.com', JA.travel, 'food'],
    ['hotpepper', 'ホットペッパー', 'https://www.hotpepper.jp', JA.travel, 'food'],
    ['paypay', 'PayPay', 'https://paypay.ne.jp', JA.money, 'wallet'],
    ['rakuten-bank', '楽天銀行', 'https://www.rakuten-bank.co.jp', JA.money, 'building'],
    ['sbi', 'SBI証券', 'https://www.sbisec.co.jp', JA.money, 'trending'],
    ['moneyforward', 'マネーフォワード', 'https://moneyforward.com', JA.money, 'wallet'],
    ['gcal', 'Google カレンダー', 'https://calendar.google.com', JA.work, 'calendar'],
    ['gdrive', 'Google ドライブ', 'https://drive.google.com', JA.work, 'folder'],
    ['notion', 'Notion', 'https://www.notion.so', JA.work, 'document'],
    ['slack', 'Slack', 'https://slack.com', JA.work, 'chat'],
    ['wikipedia-ja', 'Wikipedia', 'https://ja.wikipedia.org', JA.learn, 'book'],
    ['cookpad', 'クックパッド', 'https://cookpad.com', JA.daily, 'food'],
    ['hatena', 'はてなブックマーク', 'https://b.hatena.ne.jp', JA.news, 'star'],
    ['note', 'note', 'https://note.com', JA.learn, 'pen'],
  ]),

  ko: rows([
    ['naver', 'Naver', 'https://www.naver.com', KO.daily, 'globe', 1, 1],
    ['youtube', 'YouTube', 'https://youtube.com', KO.social, 'video', 2, 2],
    ['coupang', 'Coupang', 'https://www.coupang.com', KO.shop, 'cart', 3, 3],
    ['chatgpt', 'ChatGPT', 'https://chatgpt.com', KO.ai, 'sparkles', 4, 5],
    ['instagram', 'Instagram', 'https://instagram.com', KO.social, 'camera', 5, 6],
    ['google', 'Google', 'https://google.com', KO.daily, 'compass', 6],
    ['daum', 'Daum (Kakao)', 'https://www.daum.net', KO.daily, 'globe', undefined, 4],
    ['twitter', 'X (Twitter)', 'https://x.com', KO.social, 'chat', undefined, 7],
    ['netflix', 'Netflix', 'https://netflix.com', KO.video, 'movie', undefined, 8],
    ['spotify', 'Spotify', 'https://open.spotify.com', KO.video, 'music', undefined, 9],
    ['gmail', 'Gmail', 'https://mail.google.com', KO.daily, 'mail', undefined, 10],
    ['baemin', '배달의민족', 'https://www.baemin.com', KO.daily, 'food', undefined, 11],
    ['musinsa', 'Musinsa', 'https://www.musinsa.com', KO.shop, 'package', undefined, 12],
    ['navermail', '네이버 메일', 'https://mail.naver.com', KO.daily, 'mail'],
    ['navermap', '네이버 지도', 'https://map.naver.com', KO.travel, 'map'],
    ['kakaomap', '카카오맵', 'https://map.kakao.com', KO.travel, 'map'],
    ['kakaotalk', '카카오톡', 'https://www.kakaocorp.com/page/service/service/KakaoTalk', KO.social, 'chat'],
    ['tiktok', 'TikTok', 'https://www.tiktok.com', KO.social, 'video'],
    ['navertv', '네이버 TV', 'https://tv.naver.com', KO.social, 'tv'],
    ['afreeca', 'SOOP (아프리카TV)', 'https://www.sooplive.co.kr', KO.social, 'game'],
    ['wavve', 'wavve', 'https://www.wavve.com', KO.video, 'tv'],
    ['tving', 'TVING', 'https://www.tving.com', KO.video, 'tv'],
    ['melon', 'Melon', 'https://www.melon.com', KO.video, 'music'],
    ['webtoon', '네이버 웹툰', 'https://comic.naver.com', KO.video, 'book'],
    ['gmarket', 'G마켓', 'https://www.gmarket.co.kr', KO.shop, 'cart'],
    ['11st', '11번가', 'https://www.11st.co.kr', KO.shop, 'cart'],
    ['navershopping', '네이버 쇼핑', 'https://shopping.naver.com', KO.shop, 'cart'],
    ['oliveyoung', '올리브영', 'https://www.oliveyoung.co.kr', KO.shop, 'heart'],
    ['kurly', '컬리', 'https://www.kurly.com', KO.shop, 'leaf'],
    ['gemini', 'Gemini', 'https://gemini.google.com', KO.ai, 'sparkles'],
    ['claude', 'Claude', 'https://claude.ai', KO.ai, 'sparkles'],
    ['papago', 'Papago', 'https://papago.naver.com', KO.ai, 'globe'],
    ['canva', 'Canva', 'https://www.canva.com', KO.ai, 'design'],
    ['navernews', '네이버 뉴스', 'https://news.naver.com', KO.news, 'news'],
    ['daumnews', '다음 뉴스', 'https://news.daum.net', KO.news, 'news'],
    ['yonhap', '연합뉴스', 'https://www.yna.co.kr', KO.news, 'news'],
    ['kma', '기상청 날씨누리', 'https://www.weather.go.kr', KO.daily, 'cloud'],
    ['yanolja', '야놀자', 'https://www.yanolja.com', KO.travel, 'travel'],
    ['yeogi', '여기어때', 'https://www.goodchoice.kr', KO.travel, 'travel'],
    ['korail', '코레일', 'https://www.letskorail.com', KO.travel, 'train'],
    ['tossbank', '토스', 'https://toss.im', KO.money, 'wallet'],
    ['kakaobank', '카카오뱅크', 'https://www.kakaobank.com', KO.money, 'building'],
    ['naverfinance', '네이버 증권', 'https://finance.naver.com', KO.money, 'trending'],
    ['gcal', 'Google 캘린더', 'https://calendar.google.com', KO.work, 'calendar'],
    ['notion', 'Notion', 'https://www.notion.so', KO.work, 'document'],
    ['saramin', '사람인', 'https://www.saramin.co.kr', KO.work, 'work'],
    ['wikipedia-ko', '위키백과', 'https://ko.wikipedia.org', KO.learn, 'book'],
    ['naverdict', '네이버 사전', 'https://dict.naver.com', KO.learn, 'book'],
    ['inflearn', '인프런', 'https://www.inflearn.com', KO.learn, 'study'],
  ]),

  'zh-CN': rows([
    ['bilibili', 'Bilibili', 'https://www.bilibili.com', ZH.social, 'tv', 1, 1],
    ['youtube', 'YouTube', 'https://youtube.com', ZH.social, 'video', 2, 2],
    ['baidu', '百度', 'https://www.baidu.com', ZH.daily, 'globe', 3, 3, 'Baidu'],
    ['taobao', '淘宝', 'https://www.taobao.com', ZH.shop, 'cart', 4, 6, 'Taobao'],
    ['xiaohongshu', '小红书', 'https://www.xiaohongshu.com', ZH.social, 'book', 5, 5, 'Xiaohongshu'],
    ['chatgpt', 'ChatGPT', 'https://chatgpt.com', ZH.ai, 'sparkles', 6, 9],
    ['weibo', '微博', 'https://weibo.com', ZH.social, 'chat', undefined, 4],
    ['jd', '京东', 'https://www.jd.com', ZH.shop, 'cart', undefined, 7],
    ['zhihu', '知乎', 'https://www.zhihu.com', ZH.daily, 'book', undefined, 8],
    ['gmail', 'Gmail', 'https://mail.google.com', ZH.daily, 'mail', undefined, 10],
    ['spotify', 'Spotify', 'https://open.spotify.com', ZH.video, 'music', undefined, 11],
    ['netflix', 'Netflix', 'https://netflix.com', ZH.video, 'movie', undefined, 12],
    ['qqmail', 'QQ邮箱', 'https://mail.qq.com', ZH.daily, 'mail'],
    ['163mail', '网易邮箱', 'https://mail.163.com', ZH.daily, 'mail'],
    ['baidumap', '百度地图', 'https://map.baidu.com', ZH.travel, 'map'],
    ['amap', '高德地图', 'https://www.amap.com', ZH.travel, 'map'],
    ['douyin', '抖音', 'https://www.douyin.com', ZH.social, 'video'],
    ['douban', '豆瓣', 'https://www.douban.com', ZH.social, 'star'],
    ['tieba', '百度贴吧', 'https://tieba.baidu.com', ZH.social, 'people'],
    ['iqiyi', '爱奇艺', 'https://www.iqiyi.com', ZH.video, 'tv'],
    ['youku', '优酷', 'https://www.youku.com', ZH.video, 'tv'],
    ['tencentvideo', '腾讯视频', 'https://v.qq.com', ZH.video, 'tv'],
    ['qqmusic', 'QQ音乐', 'https://y.qq.com', ZH.video, 'music'],
    ['163music', '网易云音乐', 'https://music.163.com', ZH.video, 'headphones'],
    ['pdd', '拼多多', 'https://www.pinduoduo.com', ZH.shop, 'cart'],
    ['tmall', '天猫', 'https://www.tmall.com', ZH.shop, 'cart'],
    ['meituan', '美团', 'https://www.meituan.com', ZH.daily, 'food'],
    ['dianping', '大众点评', 'https://www.dianping.com', ZH.daily, 'food'],
    ['deepseek', 'DeepSeek', 'https://chat.deepseek.com', ZH.ai, 'sparkles'],
    ['doubao', '豆包', 'https://www.doubao.com', ZH.ai, 'sparkles'],
    ['kimi', 'Kimi', 'https://kimi.moonshot.cn', ZH.ai, 'sparkles'],
    ['baidutranslate', '百度翻译', 'https://fanyi.baidu.com', ZH.ai, 'globe'],
    ['canva', 'Canva 可画', 'https://www.canva.cn', ZH.ai, 'design'],
    ['sina', '新浪新闻', 'https://news.sina.com.cn', ZH.news, 'news'],
    ['toutiao', '今日头条', 'https://www.toutiao.com', ZH.news, 'news'],
    ['thepaper', '澎湃新闻', 'https://www.thepaper.cn', ZH.news, 'news'],
    ['weather-cn', '中国天气网', 'https://www.weather.com.cn', ZH.daily, 'cloud'],
    ['ctrip', '携程', 'https://www.ctrip.com', ZH.travel, 'travel'],
    ['12306', '12306 铁路', 'https://www.12306.cn', ZH.travel, 'train'],
    ['qunar', '去哪儿', 'https://www.qunar.com', ZH.travel, 'travel'],
    ['alipay', '支付宝', 'https://www.alipay.com', ZH.money, 'wallet'],
    ['eastmoney', '东方财富', 'https://www.eastmoney.com', ZH.money, 'trending'],
    ['feishu', '飞书', 'https://www.feishu.cn', ZH.work, 'document'],
    ['dingtalk', '钉钉', 'https://www.dingtalk.com', ZH.work, 'chat'],
    ['wpsdocs', 'WPS', 'https://www.wps.cn', ZH.work, 'document'],
    ['baike', '百度百科', 'https://baike.baidu.com', ZH.learn, 'book'],
    ['zhihu-learn', '知乎知学堂', 'https://www.zhihu.com/education/learning', ZH.learn, 'study'],
    ['icourse', '中国大学 MOOC', 'https://www.icourse163.org', ZH.learn, 'library'],
  ]),

  es: rows([
    ['google', 'Google', 'https://google.com', ES.daily, 'globe', 1, 1],
    ['youtube', 'YouTube', 'https://youtube.com', ES.social, 'video', 2, 2],
    ['amazon-es', 'Amazon', 'https://www.amazon.es', ES.shop, 'cart', 3, 4],
    ['chatgpt', 'ChatGPT', 'https://chatgpt.com', ES.ai, 'sparkles', 4, 3],
    ['maps', 'Google Maps', 'https://maps.google.com', ES.daily, 'map', 5],
    ['wikipedia', 'Wikipedia', 'https://es.wikipedia.org', ES.daily, 'book', 6],
    ['elpais', 'El País', 'https://elpais.com', ES.news, 'news', undefined, 5],
    ['marca', 'Marca', 'https://www.marca.com', ES.news, 'trophy', undefined, 6],
    ['instagram', 'Instagram', 'https://instagram.com', ES.social, 'camera', undefined, 7],
    ['twitter', 'X (Twitter)', 'https://x.com', ES.social, 'chat', undefined, 8],
    ['netflix', 'Netflix', 'https://netflix.com', ES.video, 'movie', undefined, 9],
    ['spotify', 'Spotify', 'https://open.spotify.com', ES.video, 'music', undefined, 10],
    ['gmail', 'Gmail', 'https://mail.google.com', ES.daily, 'mail', undefined, 11],
    ['wallapop', 'Wallapop', 'https://es.wallapop.com', ES.shop, 'tag', undefined, 12],
    ['whatsapp', 'WhatsApp', 'https://web.whatsapp.com', ES.social, 'chat'],
    ['tiktok', 'TikTok', 'https://www.tiktok.com', ES.social, 'video'],
    ['facebook', 'Facebook', 'https://www.facebook.com', ES.social, 'people'],
    ['twitch', 'Twitch', 'https://www.twitch.tv', ES.social, 'game'],
    ['primevideo', 'Prime Video', 'https://www.primevideo.com', ES.video, 'movie'],
    ['disney', 'Disney+', 'https://www.disneyplus.com/es-es', ES.video, 'tv'],
    ['rtveplay', 'RTVE Play', 'https://www.rtve.es/play/', ES.video, 'tv'],
    ['movistarplus', 'Movistar Plus+', 'https://ver.movistarplus.es', ES.video, 'tv'],
    ['aliexpress', 'AliExpress', 'https://es.aliexpress.com', ES.shop, 'package'],
    ['elcorteingles', 'El Corte Inglés', 'https://www.elcorteingles.es', ES.shop, 'cart'],
    ['zara', 'Zara', 'https://www.zara.com/es/', ES.shop, 'package'],
    ['mercadolibre', 'Mercado Libre', 'https://www.mercadolibre.com', ES.shop, 'cart'],
    ['idealista', 'Idealista', 'https://www.idealista.com', ES.daily, 'home'],
    ['gemini', 'Gemini', 'https://gemini.google.com', ES.ai, 'sparkles'],
    ['claude', 'Claude', 'https://claude.ai', ES.ai, 'sparkles'],
    ['copilot', 'Copilot', 'https://copilot.microsoft.com', ES.ai, 'sparkles'],
    ['deepl', 'DeepL', 'https://www.deepl.com/translator', ES.ai, 'globe'],
    ['canva', 'Canva', 'https://www.canva.com', ES.ai, 'design'],
    ['elmundo', 'El Mundo', 'https://www.elmundo.es', ES.news, 'news'],
    ['rtve', 'RTVE Noticias', 'https://www.rtve.es/noticias/', ES.news, 'news'],
    ['as', 'Diario AS', 'https://as.com', ES.news, 'trophy'],
    ['infobae', 'Infobae', 'https://www.infobae.com', ES.news, 'news'],
    ['aemet', 'AEMET', 'https://www.aemet.es', ES.daily, 'cloud'],
    ['renfe', 'Renfe', 'https://www.renfe.com', ES.travel, 'train'],
    ['booking', 'Booking.com', 'https://www.booking.com', ES.travel, 'travel'],
    ['skyscanner', 'Skyscanner', 'https://www.skyscanner.es', ES.travel, 'travel'],
    ['bizum', 'Bizum', 'https://bizum.es', ES.money, 'wallet'],
    ['caixabank', 'CaixaBank', 'https://www.caixabank.es', ES.money, 'building'],
    ['bbva', 'BBVA', 'https://www.bbva.es', ES.money, 'building'],
    ['gcal', 'Google Calendar', 'https://calendar.google.com', ES.work, 'calendar'],
    ['gdrive', 'Google Drive', 'https://drive.google.com', ES.work, 'folder'],
    ['linkedin', 'LinkedIn', 'https://www.linkedin.com', ES.work, 'work'],
    ['infojobs', 'InfoJobs', 'https://www.infojobs.net', ES.work, 'work'],
    ['duolingo', 'Duolingo', 'https://www.duolingo.com', ES.learn, 'study'],
    ['rae', 'RAE', 'https://dle.rae.es', ES.learn, 'book'],
  ]),

  fr: rows([
    ['google', 'Google', 'https://google.com', FR.daily, 'globe', 1, 1],
    ['youtube', 'YouTube', 'https://youtube.com', FR.social, 'video', 2, 2],
    ['amazon-fr', 'Amazon', 'https://www.amazon.fr', FR.shop, 'cart', 3, 4],
    ['chatgpt', 'ChatGPT', 'https://chatgpt.com', FR.ai, 'sparkles', 4, 3],
    ['maps', 'Google Maps', 'https://maps.google.com', FR.daily, 'map', 5],
    ['wikipedia', 'Wikipédia', 'https://fr.wikipedia.org', FR.daily, 'book', 6],
    ['lemonde', 'Le Monde', 'https://www.lemonde.fr', FR.news, 'news', undefined, 5],
    ['leboncoin', 'Leboncoin', 'https://www.leboncoin.fr', FR.shop, 'tag', undefined, 6],
    ['instagram', 'Instagram', 'https://instagram.com', FR.social, 'camera', undefined, 7],
    ['twitter', 'X (Twitter)', 'https://x.com', FR.social, 'chat', undefined, 8],
    ['netflix', 'Netflix', 'https://netflix.com', FR.video, 'movie', undefined, 9],
    ['spotify', 'Spotify', 'https://open.spotify.com', FR.video, 'music', undefined, 10],
    ['gmail', 'Gmail', 'https://mail.google.com', FR.daily, 'mail', undefined, 11],
    ['deezer', 'Deezer', 'https://www.deezer.com', FR.video, 'music', undefined, 12],
    ['whatsapp', 'WhatsApp', 'https://web.whatsapp.com', FR.social, 'chat'],
    ['tiktok', 'TikTok', 'https://www.tiktok.com', FR.social, 'video'],
    ['facebook', 'Facebook', 'https://www.facebook.com', FR.social, 'people'],
    ['twitch', 'Twitch', 'https://www.twitch.tv', FR.social, 'game'],
    ['primevideo', 'Prime Video', 'https://www.primevideo.com', FR.video, 'movie'],
    ['disney', 'Disney+', 'https://www.disneyplus.com/fr-fr', FR.video, 'tv'],
    ['francetv', 'france.tv', 'https://www.france.tv', FR.video, 'tv'],
    ['tf1', 'TF1+', 'https://www.tf1.fr', FR.video, 'tv'],
    ['canal', 'myCANAL', 'https://www.canalplus.com', FR.video, 'tv'],
    ['vinted', 'Vinted', 'https://www.vinted.fr', FR.shop, 'package'],
    ['cdiscount', 'Cdiscount', 'https://www.cdiscount.com', FR.shop, 'cart'],
    ['fnac', 'Fnac', 'https://www.fnac.com', FR.shop, 'cart'],
    ['aliexpress', 'AliExpress', 'https://fr.aliexpress.com', FR.shop, 'package'],
    ['gemini', 'Gemini', 'https://gemini.google.com', FR.ai, 'sparkles'],
    ['claude', 'Claude', 'https://claude.ai', FR.ai, 'sparkles'],
    ['mistral', 'Le Chat (Mistral)', 'https://chat.mistral.ai', FR.ai, 'sparkles'],
    ['deepl', 'DeepL', 'https://www.deepl.com/translator', FR.ai, 'globe'],
    ['canva', 'Canva', 'https://www.canva.com', FR.ai, 'design'],
    ['lefigaro', 'Le Figaro', 'https://www.lefigaro.fr', FR.news, 'news'],
    ['franceinfo', 'franceinfo', 'https://www.francetvinfo.fr', FR.news, 'news'],
    ['bfmtv', 'BFMTV', 'https://www.bfmtv.com', FR.news, 'news'],
    ['lequipe', "L'Équipe", 'https://www.lequipe.fr', FR.news, 'trophy'],
    ['meteofrance', 'Météo-France', 'https://meteofrance.com', FR.daily, 'cloud'],
    ['sncf', 'SNCF Connect', 'https://www.sncf-connect.com', FR.travel, 'train'],
    ['booking', 'Booking.com', 'https://www.booking.com', FR.travel, 'travel'],
    ['blablacar', 'BlaBlaCar', 'https://www.blablacar.fr', FR.travel, 'car'],
    ['airbnb', 'Airbnb', 'https://www.airbnb.fr', FR.travel, 'home'],
    ['impots', 'impots.gouv.fr', 'https://www.impots.gouv.fr', FR.money, 'building'],
    ['ameli', 'Ameli', 'https://www.ameli.fr', FR.daily, 'heart'],
    ['boursorama', 'Boursorama', 'https://www.boursorama.com', FR.money, 'trending'],
    ['gcal', 'Google Agenda', 'https://calendar.google.com', FR.work, 'calendar'],
    ['gdrive', 'Google Drive', 'https://drive.google.com', FR.work, 'folder'],
    ['linkedin', 'LinkedIn', 'https://www.linkedin.com', FR.work, 'work'],
    ['duolingo', 'Duolingo', 'https://www.duolingo.com', FR.learn, 'study'],
    ['larousse', 'Larousse', 'https://www.larousse.fr', FR.learn, 'book'],
  ]),

  de: rows([
    ['google', 'Google', 'https://google.com', DE.daily, 'globe', 1, 1],
    ['youtube', 'YouTube', 'https://youtube.com', DE.social, 'video', 2, 2],
    ['amazon-de', 'Amazon', 'https://www.amazon.de', DE.shop, 'cart', 3, 4],
    ['chatgpt', 'ChatGPT', 'https://chatgpt.com', DE.ai, 'sparkles', 4, 3],
    ['maps', 'Google Maps', 'https://maps.google.com', DE.daily, 'map', 5],
    ['wikipedia', 'Wikipedia', 'https://de.wikipedia.org', DE.daily, 'book', 6],
    ['spiegel', 'DER SPIEGEL', 'https://www.spiegel.de', DE.news, 'news', undefined, 5],
    ['kleinanzeigen', 'Kleinanzeigen', 'https://www.kleinanzeigen.de', DE.shop, 'tag', undefined, 6],
    ['instagram', 'Instagram', 'https://instagram.com', DE.social, 'camera', undefined, 7],
    ['twitter', 'X (Twitter)', 'https://x.com', DE.social, 'chat', undefined, 8],
    ['netflix', 'Netflix', 'https://netflix.com', DE.video, 'movie', undefined, 9],
    ['spotify', 'Spotify', 'https://open.spotify.com', DE.video, 'music', undefined, 10],
    ['gmail', 'Gmail', 'https://mail.google.com', DE.daily, 'mail', undefined, 11],
    ['bahn', 'Deutsche Bahn', 'https://www.bahn.de', DE.daily, 'train', undefined, 12],
    ['webde', 'WEB.DE', 'https://web.de', DE.daily, 'mail'],
    ['gmx', 'GMX', 'https://www.gmx.net', DE.daily, 'mail'],
    ['whatsapp', 'WhatsApp', 'https://web.whatsapp.com', DE.social, 'chat'],
    ['tiktok', 'TikTok', 'https://www.tiktok.com', DE.social, 'video'],
    ['facebook', 'Facebook', 'https://www.facebook.com', DE.social, 'people'],
    ['twitch', 'Twitch', 'https://www.twitch.tv', DE.social, 'game'],
    ['primevideo', 'Prime Video', 'https://www.primevideo.com', DE.video, 'movie'],
    ['disney', 'Disney+', 'https://www.disneyplus.com/de-de', DE.video, 'tv'],
    ['ardmediathek', 'ARD Mediathek', 'https://www.ardmediathek.de', DE.video, 'tv'],
    ['zdf', 'ZDFmediathek', 'https://www.zdf.de', DE.video, 'tv'],
    ['joyn', 'Joyn', 'https://www.joyn.de', DE.video, 'tv'],
    ['otto', 'OTTO', 'https://www.otto.de', DE.shop, 'cart'],
    ['zalando', 'Zalando', 'https://www.zalando.de', DE.shop, 'package'],
    ['mediamarkt', 'MediaMarkt', 'https://www.mediamarkt.de', DE.shop, 'cart'],
    ['idealo', 'idealo', 'https://www.idealo.de', DE.shop, 'tag'],
    ['gemini', 'Gemini', 'https://gemini.google.com', DE.ai, 'sparkles'],
    ['claude', 'Claude', 'https://claude.ai', DE.ai, 'sparkles'],
    ['copilot', 'Copilot', 'https://copilot.microsoft.com', DE.ai, 'sparkles'],
    ['deepl', 'DeepL', 'https://www.deepl.com/translator', DE.ai, 'globe'],
    ['canva', 'Canva', 'https://www.canva.com', DE.ai, 'design'],
    ['tagesschau', 'tagesschau', 'https://www.tagesschau.de', DE.news, 'news'],
    ['zeit', 'ZEIT ONLINE', 'https://www.zeit.de', DE.news, 'news'],
    ['faz', 'FAZ', 'https://www.faz.net', DE.news, 'news'],
    ['bild', 'BILD', 'https://www.bild.de', DE.news, 'news'],
    ['kicker', 'kicker', 'https://www.kicker.de', DE.news, 'trophy'],
    ['wetter', 'wetter.com', 'https://www.wetter.com', DE.daily, 'cloud'],
    ['booking', 'Booking.com', 'https://www.booking.com', DE.travel, 'travel'],
    ['flixbus', 'FlixBus', 'https://www.flixbus.de', DE.travel, 'bus'],
    ['check24', 'CHECK24', 'https://www.check24.de', DE.money, 'tag'],
    ['paypal', 'PayPal', 'https://www.paypal.com/de', DE.money, 'wallet'],
    ['sparkasse', 'Sparkasse', 'https://www.sparkasse.de', DE.money, 'building'],
    ['finanzen', 'finanzen.net', 'https://www.finanzen.net', DE.money, 'trending'],
    ['gcal', 'Google Kalender', 'https://calendar.google.com', DE.work, 'calendar'],
    ['gdrive', 'Google Drive', 'https://drive.google.com', DE.work, 'folder'],
    ['linkedin', 'LinkedIn', 'https://www.linkedin.com', DE.work, 'work'],
    ['xing', 'XING', 'https://www.xing.com', DE.work, 'work'],
    ['duolingo', 'Duolingo', 'https://www.duolingo.com', DE.learn, 'study'],
    ['duden', 'Duden', 'https://www.duden.de', DE.learn, 'book'],
  ]),
};

/** The region's catalog, in display order (defaults first, then the rest). Fresh copies. */
export function getSiteCatalog(lang: PresetLanguage): CatalogSite[] {
  return SITES[lang].map((site) => ({ ...site }));
}

/** Distinct category labels of a region's catalog, in first-seen order. */
export function getSiteCategories(lang: PresetLanguage): string[] {
  return Array.from(new Set(SITES[lang].map((s) => s.category)));
}

export const SITE_CATALOG_LANGUAGES: PresetLanguage[] = ['en', 'ja', 'ko', 'zh-CN', 'es', 'fr', 'de'];

/** Region names in their own language, for the picker's region switch (no i18n needed). */
export const REGION_LABELS: Record<PresetLanguage, string> = {
  en: 'Global / English',
  ja: '日本',
  ko: '한국',
  'zh-CN': '中国',
  es: 'España / Latinoamérica',
  fr: 'France',
  de: 'Deutschland',
};
