import { describe, it, expect } from 'vitest';
import { CATALOG_TITLES, NEWS_TITLES } from '../../../src/i18n/defaultTitles';
import { LOCALES } from '../../../src/i18n/resolve';
import { WIDGET_TYPES } from '../../../src/components/widgets/widgetDefinitions';

/**
 * defaultTitles.ts is static data generated by
 * scripts/generate-default-titles.mjs (`npm run i18n:default-titles`),
 * not derived from the real locales at runtime — see i18n/resolve.ts for
 * why. This is the drift check: if a widget's stock title wording
 * changes in any locale file without regenerating, this fails and says
 * so, rather than the mismatch surfacing later as a widget whose title
 * silently stops following a language switch.
 */
describe('defaultTitles: generated data matches the real locale files', () => {
  it('CATALOG_TITLES has every widget type that has a title in every locale, with the exact same text', () => {
    for (const type of WIDGET_TYPES) {
      for (const [code, locale] of Object.entries(LOCALES)) {
        if (code === 'zh') continue; // bare alias of 'zh-CN' in LOCALES; not a real SupportedLanguage code.
        const real = (locale.widgets as Record<string, { title?: string }>)[type]?.title;
        if (!real) continue;
        expect(CATALOG_TITLES[type]?.[code as keyof typeof NEWS_TITLES], `${type} / ${code}`).toBe(real);
      }
    }
  });

  it('CATALOG_TITLES has no stale entries for a type/locale the real data no longer has', () => {
    for (const [type, byLocale] of Object.entries(CATALOG_TITLES)) {
      for (const code of Object.keys(byLocale)) {
        const locale = LOCALES[code];
        expect(locale, `${type} / ${code}: locale not in LOCALES`).toBeDefined();
        const real = (locale.widgets as Record<string, { title?: string }>)[type]?.title;
        expect(real, `${type} / ${code}: stale entry, real locale has no such title`).toBe(byLocale[code as keyof typeof byLocale]);
      }
    }
  });

  it('NEWS_TITLES matches defaults.newsTitle in every locale', () => {
    for (const [code, locale] of Object.entries(LOCALES)) {
      if (code === 'zh') continue;
      expect(NEWS_TITLES[code as keyof typeof NEWS_TITLES], code).toBe(locale.defaults.newsTitle);
    }
  });
});
