import type { ElementType } from 'react';
import {
  Globe,
  Code2,
  Video,
  Mail,
  Sparkles,
  Terminal,
  Music,
  Camera,
  BookOpen,
  Heart,
  Star,
  Folder,
  ShoppingCart,
  MessageCircle,
  Calendar,
  FileText,
  Cloud,
  Newspaper,
  Gamepad2,
  Wallet,
  GraduationCap,
  Briefcase,
  Coffee,
  Pizza,
  Plane,
  Car,
  Bike,
  Home,
  Building2,
  Dumbbell,
  Palette,
  Film,
  Tv,
  Headphones,
  Mic,
  Trophy,
  Users,
  Phone,
  Bell,
  Tag,
  Package,
  CreditCard,
  DollarSign,
  TrendingUp,
  BarChart3,
  PieChart,
  ClipboardList,
  Database,
  Server,
  Sun,
  Moon,
  Zap,
  Flame,
  Droplet,
  Leaf,
  Mountain,
  Compass,
  Map,
  Anchor,
  Rocket,
  Bus,
  Train,
  Ship,
  Wrench,
  Lock,
  Key,
  Shield,
  Flag,
  Award,
  Gift,
  Cake,
  PartyPopper,
  Church,
  Library,
  Backpack,
  PenTool,
  Ruler,
  Calculator,
  Timer,
  Puzzle,
  Baby,
  Dog,
  Cat,
  Fish,
} from 'lucide-react';

/**
 * Curated icon set for Quick Dock items. Users can also type any free-form
 * emoji/short string as a custom icon; anything not found here is rendered
 * as literal text instead of a Lucide icon.
 */
export const DOCK_ICON_LIBRARY: Record<string, ElementType> = {
  globe: Globe,
  code: Code2,
  video: Video,
  mail: Mail,
  sparkles: Sparkles,
  terminal: Terminal,
  music: Music,
  camera: Camera,
  book: BookOpen,
  heart: Heart,
  star: Star,
  folder: Folder,
  cart: ShoppingCart,
  chat: MessageCircle,
  calendar: Calendar,
  document: FileText,
  cloud: Cloud,
  news: Newspaper,
  game: Gamepad2,
  wallet: Wallet,
  study: GraduationCap,
  work: Briefcase,
  coffee: Coffee,
  food: Pizza,
  travel: Plane,
  car: Car,
  bike: Bike,
  home: Home,
  building: Building2,
  fitness: Dumbbell,
  design: Palette,
  movie: Film,
  tv: Tv,
  headphones: Headphones,
  mic: Mic,
  trophy: Trophy,
  people: Users,
  phone: Phone,
  bell: Bell,
  tag: Tag,
  package: Package,
  card: CreditCard,
  money: DollarSign,
  trending: TrendingUp,
  barChart: BarChart3,
  pieChart: PieChart,
  checklist: ClipboardList,
  database: Database,
  server: Server,
  sun: Sun,
  moon: Moon,
  bolt: Zap,
  fire: Flame,
  droplet: Droplet,
  leaf: Leaf,
  mountain: Mountain,
  compass: Compass,
  map: Map,
  anchor: Anchor,
  rocket: Rocket,
  bus: Bus,
  train: Train,
  ship: Ship,
  tool: Wrench,
  lock: Lock,
  key: Key,
  shield: Shield,
  flag: Flag,
  award: Award,
  gift: Gift,
  cake: Cake,
  party: PartyPopper,
  church: Church,
  library: Library,
  backpack: Backpack,
  pen: PenTool,
  ruler: Ruler,
  calculator: Calculator,
  timer: Timer,
  puzzle: Puzzle,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  fish: Fish,
};

export const DOCK_ICON_KEYS = Object.keys(DOCK_ICON_LIBRARY);
